# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  precode-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: precode-mysql
    volumes:
      - precode-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=precode
      - MYSQL_DATABASE=precode
      - MYSQL_USER=precode
      - MYSQL_PASSWORD=precode

  # PHP 7.3 + nginx
  app:
    image: ambientum/php:latest-nginx
    container_name: precode-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql